<?php

/**
 * @file
 * Primary module hooks for ANB Account module.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_theme().
 */
function anb_account_theme($existing, $type, $theme, $path) {
  return [
    'account_menu' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
    'fuel_residues' => [
      'variables' => [],
    ],
    'fuel_transit' => [
      'variables' => [],
    ],
    'fuel_story' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_account_preprocess_page_title(&$variables) {
  $current_route = \Drupal::routeMatch()->getRouteName();

  $account_routes = [
    'anb_account.fuel_transit',
    'anb_account.fuel_story',
    'anb_account.fuel_residues',
    'anb_account.account_settings',
  ];

  if (in_array($current_route, $account_routes)) {
    $variables['title'] = new TranslatableMarkup('Personal account');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_account_preprocess_toolbar(&$variables) {
  $variables['#attached']['library'][] = 'anb_account/toolbar';
}
