<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function anb_services_theme($existing, $type, $theme, $path) {
  return [
    'calculator_forms' => [
      'variables' => [
        'forms' => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_services_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];

  if ($node->bundle() === 'service' && $variables['view_mode'] === 'full') {
    // Calculator field.
    $service_form_id = $node->field_calc_form->value;

    if ($service_form_id !== null) {
      $service_form_classes = [
        'services_delivery_form' => '\Drupal\anb_services\Form\DeliveryForm',
        'services_storage_form' => '\Drupal\anb_services\Form\StorageForm',
      ];

      if (isset($service_form_classes[$service_form_id])) {
        $form_class = $service_form_classes[$service_form_id];

        if (class_exists($form_class)) {
          $variables['content']['calc_form'] = \Drupal::formBuilder()->getForm($form_class);
        }
      }
    }

    // Page title.
    $page_title = $node->field_page_title->value;
    if (!is_null($page_title)) {
      $variables['page_title'] = $page_title;
    } else {
      $variables['page_title'] = $node->label();
    }

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_services_preprocess_page(&$variables) {
  if (isset($variables['node'])) {
    $node = $variables['node'];

    if ($node->bundle() === 'service') {
      if ($node->body->isEmpty() === false) {
        $variables['page']['bottom_content']['service_description'] = [
          '#type' => 'markup',
          '#markup' => '<section class="bottom-description container body">' . $node->body->value . '</section>',
        ];
      }
    }
  }
}
