<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_services_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];

  if ($node->bundle() === 'service' && $variables['view_mode'] === 'full') {
    $service_form_id = $node->field_calc_form->value;

    if ($service_form_id === null) {
      return;
    }

    $service_form_classes = [
      'services_delivery_form' => '\Drupal\anb_services\Form\DeliveryForm',
      'services_transshipment_form' => '\Drupal\anb_services\Form\TransshipmentForm',
      'services_storage_form' => '\Drupal\anb_services\Form\StorageForm',
    ];

    if (isset($service_form_classes[$service_form_id])) {
      $form_class = $service_form_classes[$service_form_id];

      if (class_exists($form_class)) {
        $variables['content']['calc_form'] = \Drupal::formBuilder()->getForm($form_class);
      }
    }

  }
}
