unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: field--type-string-long
time_limit: 8
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_calcrequest_form: true
  contact_message_callbackform_form: true
  contact_message_consultform_form: true
  contact_message_discountform_form: true
  contact_message_feedback_form: true
  contact_message_jobform_form: true
  contact_message_orderform_form: true
  contact_message_personal_form: true
  contact_message_questionform_form: true
  node_article_form: false
  node_news_form: false
  node_page_form: false
  node_product_form: false
  node_service_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
langcode: ru
