<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\anb_catalog\CatalogManager;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function anb_catalog_theme($existing, $type, $theme, $path) {
  return [
    'catalog_filter_footer' => [
      'variables' => [
        'category_name' => NULL,
        'category_url' => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function anb_catalog_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Allow only top-level categories for product node.
  $product_forms = [
    'node_product_form',
    'node_product_edit_form'
  ];

  if (in_array($form_id, $product_forms)) {
    if (!isset($form['field_category'])) {
      return;
    }

    $catalog_manager = new CatalogManager();

    $options = [
      '_none' => 'Не указано',
    ] + $catalog_manager->getTopLevelCategories('catalog');

    $form['field_category']['widget']['#options'] = $options;
  }

  // Products view categories filter.
  if ($form['#id'] === 'views-exposed-form-products-all') {
    if (!isset($form['category'])) {
      return;
    }

    $form['#attributes']['class'][] = 'filters';
    $form['category']['#type'] = 'radios';
    $form['actions']['submit']['#attributes']['class'][] = 'visually-hidden';

    // Set available category options.
    $catalog_manager = new CatalogManager();
    $options = [] + $catalog_manager->getTopLevelCategories('catalog');
    $form['category']['#options'] = $options;

    // Set dynamic form footer.
    $category_id = $form_state->getUserInput()['category'];
    $category_name = $form['category']['#options'][$category_id];
    $category_url = Url::fromRoute(
      'entity.taxonomy_term.canonical',
      ['taxonomy_term' => $category_id], ['absolute' => false])
      ->toString();

    if (!is_null($category_id)) {
      $form['bottom'] = [
        '#theme' => 'catalog_filter_footer',
        '#category_name' => $category_name,
        '#category_url' => $category_url,
        '#weight' => 100,
      ];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function anb_catalog_preprocess_radios(&$variables) {
  if ($variables['element']['#name'] === 'category') {
    $variables['attributes']['class'][] = 'tabs';
  }
}
